feat(front/back): Reset password flow
c3pm-labs/platform pull request #22
Opened 2020-12-06 13:26 UTC by angela-boyadjian

2020-12-09 15:14 UTC, gabrielcolson commented on back/src/services/ForgotService.ts
> +import sgMail = require('@sendgrid/mail');
```suggestion
import * as sgMail from "@sendgrid/mail"
```

2020-12-12 00:01 UTC, chloebourbion requested changes
![image](https://user-images.githubusercontent.com/37622266/101965557-5d2ad500-3c15-11eb-80cd-20d8af36cd8b.png)
On mobile can you make the input and the button take all the width and make the text smaller?

What do you think of "An email has been send! check your inbox" as an explanation sentence?

2020-12-12 00:04 UTC, chloebourbion requested changes

2020-12-12 00:04 UTC, chloebourbion commented on front/pages/forgot_password.tsx
> +    margin: 'auto',
you shouldn't use `margin: auto` to center your content, try `alignItems: 'center'` or `justifyContent: 'center'`

2020-12-12 00:04 UTC, chloebourbion commented on front/pages/forgot_password.tsx
> +    fontSize: 24,
can you reduce the fontSize just a little?

2021-01-06 16:08 UTC, gabrielcolson requested changes

2021-01-06 16:08 UTC, gabrielcolson commented on back/src/graphql/types/User.ts
> +    t.model.resetPasswordToken();
remove this

2021-01-06 16:08 UTC, gabrielcolson commented on back/.envrc.example
> +export FORGOT_URL=http://localhost:3000/reset_password?token=
change this to `FRONTEND_URL` and use only the base URL

2021-01-06 16:08 UTC, gabrielcolson commented on back/src/services/ForgotService.ts
> +    });
Switch both statements and check that the user exists before sending him an email

2021-01-06 16:08 UTC, gabrielcolson commented on front/package.json
> +    "uuid": "^8.3.1",
Remove this unused dependency

2021-01-06 16:08 UTC, gabrielcolson commented on front/pages/forgot_password.tsx
> +          forgot(email);
missing await

2021-01-06 16:08 UTC, gabrielcolson commented on front/pages/reset_password.tsx
> +          reset({ token: token.toString(), password: params.password });
missing await

2021-01-07 13:58 UTC, gabrielcolson approved these changes

2021-01-07 15:33 UTC, chloebourbion approved these changes

2021-01-07 16:34 UTC, merged