WIP: feat(plateform): add settings page, settings update mutations
c3pm-labs/platform pull request #5
Opened 2020-11-07 01:39 UTC by MinaBarry

PROBLEME:
- Problème d’authentification: User déconnecter lors du refresh de la page ou apres avoir update un setting -> empêche de récupérer l’ID de l’user dans les requêtes update. 
- Après avoir changer le username dans les settings, l’avatar dans la barre en haut a droite reste comme l’ancien

A RAJOUTER / A ENLEVER:
- Enlever la partie avatar du settings
- Rajouter l’update de mot de passe (back et front)

2020-12-12 19:14 UTC, chloebourbion requested changes

2020-12-12 19:14 UTC, chloebourbion commented on front/components/Avatar/index.tsx
> +  const pictureClass = clsx(styles.picture, classes?.picture, stylePicture);
you don't need `stylePicture` this is what the ` classes?.picture`element is for

2020-12-12 19:54 UTC, chloebourbion requested changes
The update password doesn't work, I still nee my old password to login
On the update forms the values should be set by default to my current values (except password which should be empty)
When I click on "save" and it works it could be great to have a snackbar or a message telling me that my infos where successfully updated (but maybe we can do that on another pr)

2020-12-14 20:27 UTC, ItagibaALIX approved these changes

2020-12-15 10:40 UTC, chloebourbion approved these changes

2020-12-15 10:40 UTC, merged