Feat: tags (add tags in DB + search with tags)
c3pm-labs/platform pull request #59
Opened 2021-04-16 17:26 UTC by chloebourbion

get tags when publishing and stock them in DB + add tags option when searching for packages

2021-04-18 20:05 UTC, angela-boyadjian submitted a review, later dismissed

2021-04-19 06:05 UTC, MinaBarry approved these changes, later dismissed

2021-05-04 14:33 UTC, angela-boyadjian approved these changes, later dismissed

2021-05-07 18:12 UTC, gabrielcolson requested changes

2021-05-07 18:12 UTC, gabrielcolson commented on back/package.json
> +    "prisma": "^2.21.2",
Prisma is already defined as a dev dependency. You can remove it from the dependencies.

2021-05-09 23:58 UTC, angela-boyadjian approved these changes, later dismissed

2021-05-11 15:32 UTC, angela-boyadjian commented
I think we need to have the tags array in the Package table instead of the Versions. Otherwise, we will have serious lack of optimization during the Search since we will search N tags for N versions so 1 additional iteration per version per package.

Ideally, I think we'd like to have a Tags table where each tags contains a list of packages containing that tag but for now we should at least have the Tags in Package.

2021-05-15 17:23 UTC, gabrielcolson approved these changes

2021-05-17 14:38 UTC, merged