feat: add beautiful loader
c3pm-labs/platform pull request #65
Opened 2021-04-29 22:27 UTC by ItagibaALIX

2021-05-08 16:41 UTC, chloebourbion requested changes

2021-05-08 16:41 UTC, chloebourbion commented on front/components/pages/Settings/Profile/index.tsx
> +      </div>
It seems like it's the same code everywhere with almost the same style
You could do a component Loader which return this code and has his style

2021-05-11 18:34 UTC, gabrielcolson approved these changes

2021-05-12 07:59 UTC, chloebourbion approved these changes

2021-05-12 08:04 UTC, merged